#!/usr/bin/env python3
"""Generate docs/_recent_updates.md from real git history.

Runs before `mkdocs build`/`mkdocs gh-deploy` so the "Recent Updates"
section on the homepage always reflects actual commit history instead
of a hand-maintained list that goes stale the moment a new page lands.
"""

import re
import subprocess
from pathlib import Path

DOCS_DIR = Path("docs")
OUTPUT = DOCS_DIR / "_recent_updates.md"
MAX_ENTRIES = 10

# nav label lookup: mirror mkdocs.yml's human-readable titles so the
# generated list doesn't show raw filenames like "35_ghostexec..."
TITLE_OVERRIDES = {
    "index.md": "Home",
}


def first_h1(path: Path) -> str | None:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None
    match = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    if not match:
        return None
    title = match.group(1).strip()
    # Strip a leading "Architecture NN — " prefix for a cleaner list —
    # the number/category is already implied by grouping in the nav.
    title = re.sub(r"^Architecture \d+\s*[—-]\s*", "", title)
    return title


def most_recent_docs(limit: int) -> list[tuple[str, str]]:
    """Return (date, relative_path) for the most recently touched docs
    pages, most recent first, deduplicated by path."""
    raw = subprocess.run(
        [
            "git", "log",
            "--name-only",
            "--pretty=format:%ad|%H",
            "--date=format:%Y-%m-%d",
            "--", str(DOCS_DIR),
        ],
        capture_output=True, text=True, check=True,
    ).stdout

    index_path = (DOCS_DIR / "index.md").as_posix()
    output_path = OUTPUT.as_posix()

    seen: set[str] = set()
    results: list[tuple[str, str]] = []
    current_date = None
    for line in raw.splitlines():
        if "|" in line and len(line.split("|")) == 2 and line.split("|")[1].strip() and not line.endswith(".md"):
            current_date = line.split("|")[0]
            continue
        if not line.endswith(".md"):
            continue
        normalized = line.replace("\\", "/")
        if normalized in seen:
            continue
        seen.add(normalized)
        if normalized in (index_path, output_path):
            continue  # never list the homepage or the generated file itself
        results.append((current_date, normalized))
        if len(results) >= limit:
            break
    return results


def main() -> None:
    entries = most_recent_docs(MAX_ENTRIES)
    lines = ["<!-- AUTO-GENERATED by scripts/gen_recent_updates.py — do not edit by hand -->", ""]
    lines.append("| Date | Page |")
    lines.append("|---|---|")
    for date, rel_path in entries:
        file_path = Path(rel_path)
        doc_rel = file_path.relative_to(DOCS_DIR)
        filename = doc_rel.name
        title = TITLE_OVERRIDES.get(filename) or first_h1(file_path) or filename
        # mkdocs internal doc links are relative to docs/, using the
        # source .md path (mkdocs resolves these to the built .html).
        link_target = str(doc_rel).replace("\\", "/")
        lines.append(f"| {date} | [{title}]({link_target}) |")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT} with {len(entries)} entries")


if __name__ == "__main__":
    main()
